apiVersion: apps/v1
kind: Deployment
metadata:
  name: minecraft
spec:
  template:
    spec:
      containers:
        - name: minecraft
          env:
            - name: MOTD
              value: "PROD - be nice, people are playing"
            - name: DIFFICULTY
              value: "hard"
            - name: MODE
              value: "survival"
            - name: MAX_PLAYERS
              value: "20"
          resources:
            requests:
              cpu: "500m"
              memory: "1536Mi"
            limits:
              cpu: "1500m"
              memory: "2Gi"
