apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: minecraft-staging

resources:
  - ../../base

images:
  - name: docker.io/itzg/minecraft-server
    newTag: "2026.6.0"

patches:
  - path: patch.yaml
