apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: minecraft-staging
resources:
- ../../base
images:
- name: docker.io/itzg/minecraft-server
  newTag: 2026.7.2
  digest: sha256:6ec1110e4d9236d00ae9436a3e4a5929583e5b19cc94b756a7c603f7cf647a77
patches:
- path: patch.yaml
